# Generated by Django 5.1.7 on 2025-04-12 17:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('telefone', models.CharField(max_length=15, null=True)),
                ('curso', models.CharField(max_length=50, null=True)),
                ('vendedor', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Camiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_parcela', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('forma_pag_op', models.CharField(max_length=200, null=True)),
                ('data_limite_pedidos', models.DateField()),
                ('data_pag1', models.DateField(help_text='Total ou primeira parcela')),
                ('data_pag2', models.DateField(blank=True, help_text='Não precisa colocar', null=True)),
                ('turnos', models.CharField(max_length=50)),
                ('cores', models.TextField(help_text='Digite as cores separadas por vírgula. Ex: azul, vermelho, verde', null=True)),
                ('cursos', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='')),
                ('pix_qr_code_parcela', models.ImageField(default='', upload_to='qrcode_parcela_camisetas/')),
                ('pix_qr_code_total', models.ImageField(default='', upload_to='qrcode_total_camisetas/')),
                ('pix_chave_parcela', models.TextField(default='', max_length=300)),
                ('pix_chave_total', models.TextField(default='', max_length=300)),
                ('estilos', models.CharField(default='', max_length=50)),
                ('tamanhos', models.JSONField(default=dict)),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camisetas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstiloTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(choices=[('Babylook', 'BabyLook'), ('Normal', 'Normal'), ('Infantil', 'Infantil')], max_length=20)),
                ('tamanho', models.CharField(choices=[('PP', 'Extra Pequeno'), ('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra Grande')], max_length=5)),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilos_tamanhos', to='ifshop.camiseta')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemCamiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(null=True, upload_to='imagens_camisetas/')),
                ('principal', models.BooleanField(default=False)),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='ifshop.camiseta')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estampa', models.CharField(max_length=50)),
                ('numero_estampa', models.CharField(max_length=50)),
                ('cor_escolhida', models.CharField(max_length=50, null=True)),
                ('tamanho', models.CharField(max_length=10)),
                ('estilo', models.CharField(default='', max_length=20)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('forma_pag', models.TextField(max_length=300, null=True)),
                ('status', models.CharField(default='Pendente', max_length=100)),
                ('revisado', models.BooleanField(default=True)),
                ('visto', models.BooleanField(default=False)),
                ('comprovante_total', models.ImageField(default='', upload_to='qrcode_total_camisetas/')),
                ('comprovante_parcela1', models.ImageField(default='', upload_to='qrcode_total_camisetas/')),
                ('comprovante_parcela2', models.ImageField(default='', upload_to='qrcode_total_camisetas/')),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifshop.camiseta')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
