# Generated by Django 5.2.7 on 2025-10-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtobase',
            name='forma_pag_op',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='produtobase',
            name='preco_parcela',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
