# Generated by Django 5.2.5 on 2025-10-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtobase',
            old_name='cursos',
            new_name='curso',
        ),
    ]
