# Generated by Django 5.1.3 on 2024-11-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='cores',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_estampa',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='camiseta',
            name='cores',
            field=models.ManyToManyField(blank=True, to='ifshop.cor'),
        ),
    ]
