# Generated by Django 5.1.3 on 2024-12-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustomizado',
            name='é_vendedor',
            field=models.BooleanField(default=False),
        ),
    ]
