# Generated by Django 5.1.7 on 2025-04-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloCamiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(choices=[('Babylook', 'BabyLook'), ('Normal', 'Normal'), ('Infantil', 'Infantil')], max_length=20)),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilos_cadastrados', to='ifshop.camiseta')),
            ],
        ),
        migrations.CreateModel(
            name='TamanhoPorEstilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('PP', 'Extra Pequeno'), ('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra Grande')], max_length=5)),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos_disponiveis', to='ifshop.estilocamiseta')),
            ],
        ),
    ]
