# Generated by Django 5.1.3 on 2024-11-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0002_cor_remove_camiseta_cores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camiseta',
            name='imagens',
        ),
        migrations.CreateModel(
            name='ImagemCamiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='camisetas/')),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='ifshop.camiseta')),
            ],
        ),
    ]
