# Generated by Django 5.1.3 on 2024-12-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0002_rename_usuario_camiseta_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustomizado',
            name='nome',
            field=models.CharField(default='Sem Nome Temporário', max_length=150),
        ),
    ]
