# Generated by Django 5.1.3 on 2024-11-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0002_remove_usuariocustom_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustom',
            name='cursos',
            field=models.CharField(max_length=20, verbose_name='Curso'),
        ),
    ]
