# Generated by Django 5.1.7 on 2025-04-06 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0002_estilocamiseta_tamanhoporestilo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamanhoporestilo',
            name='estilo',
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='tamanhos',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='EstiloTamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(choices=[('Babylook', 'BabyLook'), ('Normal', 'Normal'), ('Infantil', 'Infantil')], max_length=20)),
                ('tamanho', models.CharField(choices=[('PP', 'Extra Pequeno'), ('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Extra Grande')], max_length=5)),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilos_tamanhos', to='ifshop.camiseta')),
            ],
        ),
        migrations.DeleteModel(
            name='EstiloCamiseta',
        ),
        migrations.DeleteModel(
            name='TamanhoPorEstilo',
        ),
    ]
