# Generated by Django 5.1.3 on 2024-12-18 12:39

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0002_alter_usuariocustomizado_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustomizado',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
