# Generated by Django 5.1.7 on 2025-05-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0002_alter_estilotamanho_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comprovante_parcela1',
            field=models.ImageField(default='', null=True, upload_to='qrcode_total_camisetas/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comprovante_parcela2',
            field=models.ImageField(default='', null=True, upload_to='qrcode_total_camisetas/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comprovante_total',
            field=models.ImageField(default='', null=True, upload_to='qrcode_total_camisetas/'),
        ),
    ]
