# Generated by Django 5.1.3 on 2024-12-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0002_usuariocustomizado_é_vendedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariocustomizado',
            old_name='é_vendedor',
            new_name='is_seller',
        ),
    ]
