# Generated by Django 5.1.3 on 2024-12-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0003_rename_é_vendedor_usuariocustomizado_is_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariocustomizado',
            old_name='is_seller',
            new_name='vendedor',
        ),
    ]
