# Generated by Django 5.1.7 on 2025-04-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0003_remove_tamanhoporestilo_estilo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camiseta',
            name='pix_chave_parcela',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='camiseta',
            name='pix_chave_total',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='camiseta',
            name='pix_qr_code_parcela',
            field=models.ImageField(default='', upload_to='qrcode_parcela_camisetas/'),
        ),
        migrations.AddField(
            model_name='camiseta',
            name='pix_qr_code_total',
            field=models.ImageField(default='', upload_to='qrcode_total_camisetas/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprovante_parcela1',
            field=models.ImageField(default='', upload_to='qrcode_total_camisetas/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprovante_parcela2',
            field=models.ImageField(default='', upload_to='qrcode_total_camisetas/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprovante_total',
            field=models.ImageField(default='', upload_to='qrcode_total_camisetas/'),
        ),
    ]
