# Generated by Django 5.1.3 on 2024-12-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0003_usuariocustomizado_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustomizado',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
