# Generated by Django 5.1.3 on 2024-11-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0003_remove_camiseta_imagens_imagemcamiseta'),
    ]

    operations = [
        migrations.AddField(
            model_name='camiseta',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ImagemCamiseta',
        ),
    ]
