# Generated by Django 5.1.3 on 2024-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0003_alter_usuariocustomizado_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocustomizado',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
