# Generated by Django 5.1.7 on 2025-05-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0003_alter_camiseta_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='comprovante_parcela1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='qrcode_total_camisetas/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comprovante_parcela2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='qrcode_total_camisetas/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='comprovante_total',
            field=models.ImageField(blank=True, default='', null=True, upload_to='qrcode_total_camisetas/'),
        ),
    ]
