# Generated by Django 5.1.3 on 2024-11-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0003_alter_usuariocustom_cursos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariocustom',
            old_name='cursos',
            new_name='cursos_user',
        ),
    ]
