# Generated by Django 5.1.3 on 2024-12-27 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0004_alter_usuariocustomizado_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_camisetas/')),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iamgens', to='ifshop.camiseta')),
            ],
        ),
    ]
