# Generated by Django 5.1.7 on 2025-08-11 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0004_alter_pedido_comprovante_parcela1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='cursos',
        ),
        migrations.AlterField(
            model_name='usuariocustomizado',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifshop.curso'),
        ),
        migrations.AddField(
            model_name='camiseta',
            name='cursos',
            field=models.ManyToManyField(to='ifshop.curso'),
        ),
    ]
