# Generated by Django 5.1.3 on 2024-11-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0004_rename_cursos_usuariocustom_cursos_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioCustom',
        ),
    ]
