# Generated by Django 5.1.7 on 2025-04-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0004_camiseta_pix_chave_parcela_camiseta_pix_chave_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pag',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
