# Generated by Django 5.2.7 on 2025-12-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0004_vendecrud'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustomizado',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
