# Generated by Django 5.2.7 on 2025-12-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0005_usuariocustomizado_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtobase',
            name='estoque',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuariocustomizado',
            name='foto',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
