# Generated by Django 5.1.3 on 2025-01-03 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0005_imagens'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemCamiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_camisetas/')),
                ('principal', models.BooleanField(default=False)),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='ifshop.camiseta')),
            ],
        ),
        migrations.DeleteModel(
            name='Imagens',
        ),
    ]
