# Generated by Django 5.2.5 on 2025-09-05 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0005_curso_remove_camiseta_cursos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='camiseta',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='cores',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='data_limite_pedidos',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='data_pag1',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='data_pag2',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='forma_pag_op',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='pix_chave_parcela',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='pix_chave_total',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='pix_qr_code_parcela',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='pix_qr_code_total',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='preco_parcela',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='turnos',
        ),
        migrations.RemoveField(
            model_name='camiseta',
            name='vendedor',
        ),
        migrations.CreateModel(
            name='PedidoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao_escolhida', models.CharField(max_length=50, null=True)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('forma_pag', models.TextField(max_length=300, null=True)),
                ('status', models.CharField(default='Pendente', max_length=100)),
                ('revisado', models.BooleanField(default=True)),
                ('visto', models.BooleanField(default=False)),
                ('comprovante_total', models.ImageField(blank=True, default='', null=True, upload_to='comprovante_total_produto/')),
                ('comprovante_parcela1', models.ImageField(blank=True, default='', null=True, upload_to='comprovante_parcela1_produto/')),
                ('comprovante_parcela2', models.ImageField(blank=True, default='', null=True, upload_to='comprovante_parcela2_produto/')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCamiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estampa', models.CharField(max_length=50)),
                ('numero_estampa', models.CharField(max_length=50)),
                ('tamanho', models.CharField(max_length=10)),
                ('estilo', models.CharField(default='', max_length=20)),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifshop.camiseta')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camisetas', to='ifshop.pedidobase')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_parcela', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('forma_pag_op', models.CharField(max_length=200, null=True)),
                ('data_limite_pedidos', models.DateField()),
                ('data_pag1', models.DateField(help_text='Total ou primeira parcela')),
                ('data_pag2', models.DateField(blank=True, help_text='Não precisa colocar', null=True)),
                ('turma', models.CharField(max_length=50)),
                ('turnos', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('pix_qr_code_parcela', models.ImageField(default='', upload_to='qrcode_parcela_produtos/')),
                ('pix_qr_code_total', models.ImageField(default='', upload_to='qrcode_total_produtos/')),
                ('pix_chave_parcela', models.TextField(default='', max_length=300)),
                ('pix_chave_total', models.TextField(default='', max_length=300)),
                ('opcoes', models.TextField(help_text='Digite as opções separadas por vírgula. Ex: azul, vermelho, verde', null=True)),
                ('cursos', models.ManyToManyField(to='ifshop.curso')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedidobase',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_base', to='ifshop.produtobase'),
        ),
        migrations.CreateModel(
            name='ImagemProdutoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(null=True, upload_to='imagens_produtos/')),
                ('principal', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='ifshop.produtobase')),
            ],
        ),
        migrations.AddField(
            model_name='camiseta',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camisetas', to='ifshop.produtobase'),
        ),
        migrations.DeleteModel(
            name='ImagemCamiseta',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
