# Generated by Django 5.2.7 on 2025-12-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0006_produtobase_estoque_alter_usuariocustomizado_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtobase',
            name='tem_estoque',
            field=models.BooleanField(default=False),
        ),
    ]
