# Generated by Django 5.1.3 on 2025-01-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0006_imagemcamiseta_delete_imagens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='usuario',
            new_name='cliente',
        ),
    ]
