# Generated by Django 5.2.7 on 2025-12-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0007_produtobase_tem_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidobase',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtobase',
            name='estoque',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade em estoque'),
        ),
    ]
