# Generated by Django 5.1.3 on 2025-01-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0007_rename_usuario_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='pendente', max_length=100),
        ),
    ]
