# Generated by Django 5.1.3 on 2025-01-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0008_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='camiseta',
            name='forma_pag_op',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='forma_pag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='Pendente', max_length=100),
        ),
    ]
