# Generated by Django 5.2.7 on 2025-12-22 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0008_pedidobase_data_entrega_alter_produtobase_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendecrud',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Codigo2FA',
        ),
    ]
