# Generated by Django 5.1.3 on 2025-01-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0011_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='revisado',
            field=models.BooleanField(default=True),
        ),
    ]
