# Generated by Django 5.1.3 on 2025-02-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0012_pedido_revisado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemcamiseta',
            name='imagem',
            field=models.ImageField(null=True, upload_to='imagens_camisetas/'),
        ),
    ]
