# Generated by Django 5.1.3 on 2025-02-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0013_alter_imagemcamiseta_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamisetaCor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cores_disponiveis', to='ifshop.camiseta')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifshop.cor')),
            ],
            options={
                'unique_together': {('camiseta', 'cor')},
            },
        ),
    ]
