# Generated by Django 5.1.3 on 2025-02-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0014_camisetacor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camiseta',
            name='cores',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cor',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cor_escolhida',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CamisetaCor',
        ),
        migrations.DeleteModel(
            name='Cor',
        ),
        migrations.AddField(
            model_name='camiseta',
            name='cores',
            field=models.TextField(help_text='Digite as cores separadas por vírgula. Ex: azul, vermelho, verde', null=True),
        ),
    ]
