# Generated by Django 5.1.3 on 2025-02-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifshop', '0015_remove_camiseta_cores_remove_pedido_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
